### ISSUE TITLE
Angular velocity on Rigibody2D is not working.

### ISSUE THREAD

**Issue by Galllaa** [appsinacup/godot-rapier-physics#104]
**Describe the bug**
Angular velocity on Rigibody2D is not working.

**To Reproduce**
Create Rigibody2D set gravity_scale = 0 then go to Angular under velocity set any number.

**Expected behavior**
Rigibody should spin.

**Environment (please complete the following information):**
 - OS Windows 10
 - Version 0.6.21
 - Godot Version [v4.2]
- Type [simd single]

**Example project(zip)**
No need for that.

**Comment by thejoecode** [comment]
Looks like angular velocity 0.0 is always applied - made a comment on the code review here: https://github.com/appsinacup/godot-rapier-2d/commit/2089c376b2acd5333aa811a647f6441e11e4bc54#r142293071
