### ISSUE TITLE
Regressions with physics server collide_shape() query

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [appsinacup/godot-rapier-physics#105]
**Describe the bug**
get_world_2d().direct_space_state.collide_shape() returns points in the reversed order. And it doesn't work against a circle body when the query shape is also a circle.

**To Reproduce**
Steps to reproduce:
1. Create a PhysicsShapeQueryParameters2D instance, set its shape to a CircleShape2D, adjust query transform so it will collide with a non circle body in the game world.
2. Call get_world_2d().direct_space_state.collide_shape() in the physics frame with the max collisions set to 1.
3. Draw the two Vector2 points in the returned array.
4. See that the first point is the collision occuring inside the passed shape, the second is inside the colliding shape in the world.
5. Do the same against a circle in the game world.
6. See that the first point is same as the collision point.
7. Change query shape to something else.
8 See that it works fine against circles in the game world.

**Expected behavior**
When using GodotPhysics2D, the order of points in the array is reversed, circle to circle collide_shape() queries work fine.

**Screenshots**
The first point is colored red in all screenshots.
Rapier2D, query shape is circle:
![image](https://github.com/appsinacup/godot-rapier-2d/assets/84380947/34fd32bb-095a-4ffb-89d7-70d95459f447)

GodotPhysics2D, query shape is circle:
![image](https://github.com/appsinacup/godot-rapier-2d/assets/84380947/128fcf48-9860-470b-a285-a36178f12cc8)

Rapier2D, query shape is rectangle:
![image](https://github.com/appsinacup/godot-rapier-2d/assets/84380947/f4c73f0f-ead4-4d4c-9932-31ea024b4f80)

GodotPhysics2D, query shape is rectangle:
![image](https://github.com/appsinacup/godot-rapier-2d/assets/84380947/4f688ad2-96e5-4c15-89de-aafcadfdaf70)

**Environment (please complete the following information):**
 - OS: Windows
 - Version: v0.6.21
 - Godot Version: v4.2.2 mono
 - Type [simd single]

**Example project(zip)**
[project.zip](https://github.com/appsinacup/godot-rapier-2d/files/15457876/project.zip)

**Comment by Ughuuu** [comment]
It's still weird how Rapier for circle puts both points inside. I wonder why. The order should be fixed now, idk if that is corect or not that they are both inside for that case though.
