### ISSUE TITLE
Removing shapes from a body doesn't work

### ISSUE THREAD

**Issue by lonevox** [appsinacup/godot-rapier-physics#106]
**Describe the bug**
With GodotPhysics2D I can remove shapes from a body when the shape is collided with via `PhysicsServer2D.body_remove_shape()`. Shapes don't seem to be removed properly in Rapier2D.

**To Reproduce**
1. Download the example project.
2. Run it (the project uses GodotPhysics2D by default). You will see that the shapes are removed when colliding with the floor (the drawn polygons remain to make it easier to see that the body no longer has shapes and falls through the floor as expected).
3. Switch the physics engine to Rapier2D. The shapes aren't removed when colliding with the floor, and behave strangely as they would normally tip over (you can see them tip over if you make `destroy_shape_on_collision` false in `rigid_body_2d.gd`).

**Expected behavior**
Rapier2D should behave in the same way as GodotPhysics2D.

**Videos**
GodotPhysics2D:

https://github.com/appsinacup/godot-rapier-2d/assets/38600896/0a7a5631-61c3-411f-81a4-c875ac2a1626

Rapier2D:

https://github.com/appsinacup/godot-rapier-2d/assets/38600896/7960fb6c-e400-416b-a3b6-d5ff08dae2a6

**Environment:**
 - OS: Windows
 - Version: v0.6.21
 - Godot Version: v4.3-beta1
- Type: simd single

**Example project(zip)**

[RapierBug.zip](https://github.com/user-attachments/files/15598289/RapierBug.zip)

**Comment by Ughuuu** [comment]
Fix by re-updating the shape indexes after a shape is deleted/removed.
