### ISSUE TITLE
Ghost collisions

### ISSUE THREAD

**Issue by AntonBergaker** [appsinacup/godot-rapier-physics#122]
Going between two colliders can introduce ghost collisions.

Here you can see an example where the player does a small bounce up when going between two shapes towards the end of the video.

https://github.com/appsinacup/godot-rapier-physics/assets/12459883/e0a07116-742a-49b0-b072-67864c1d010a

This seems to depend on an upstream rapier thing.
https://github.com/dimforge/rapier/issues/669

**Comment by Ughuuu** [comment]
![ghost_collisions](https://github.com/user-attachments/assets/6fe7ca18-05b8-47ee-bcfe-4b5e96e3c0aa)

Finally fixed
