### ISSUE TITLE
physics determinism fails when recreating the same scene

### ISSUE THREAD

**Issue by halicarnassus** [appsinacup/godot-rapier-physics#134]
**Describe the bug**

When all bodies part of a simulation are contained in a scene that is recreated the outcome can vary

**To Reproduce**

Turn on visible collision shapes in the Editor

Open the project and hit RESET a couple of times and eventually the ragdoll will fall down the stairs differently

**Expected behavior**

The ragdoll falls down identically, never changing the outcome

**Environment:**
 - OS: Windows 11
 - Version 0.7.6
 - Godot Version v4.2.1.stable.official
 - Type enhanced determinism 2d

**Example project(zip)**

[determintest.zip](https://github.com/user-attachments/files/16066813/determintest.zip)

**Comment by Ughuuu** [comment]
Strange, seems to be quite deterministic for on my machine. Always falls the same. I'll test a bit more.

**Comment by Ughuuu** [comment]
For reference, I am checking the state of the space by running:
```gdscript
var file = FileAccess.open("user://space.json", FileAccess.WRITE)
var space_state = RapierPhysicsServer2D.space_export_json(get_viewport().world_2d.space)
```
And making sure that after resets it doesn't change.

**Comment by Ughuuu** [comment]
https://github.com/appsinacup/godot-rapier-physics/assets/2369380/b22a31f5-dd0c-44f4-a1e7-2cc07a128f0a
