### ISSUE TITLE
Got some weird errors on RapierArea2D

### ISSUE THREAD

**Issue by onkeltora** [appsinacup/godot-rapier-physics#147]
**Describe the bug**

Hi everyone.

I don't know what exactly the error means.

As i have added a few Enemies within my game that following the player with Area2Ds to damage the player on contact.

Is there a way to shortrepair the error, or maybe to mute it ?
Everything works fine, but it keeps spamming my debug window. O.o (5k+ in 2 Minutes)

Switching back to Default Physics stops the error, BUT.. all Colliders and Areas stop working, too... :/

**Error-Code**
```
E 0:00:21:0120   RapierArea2D::on_body_enter: Condition "monitored_objects.has(handle_pair_hash)" is true.
  <C++-Quelle>   src\bodies\rapier_area_2d.cpp:50 @ RapierArea2D::on_body_enter()
```

**To Reproduce**

Setting up some CollisionLayer2Ds within Area2D on enemies directing to player position

**Environment:**
 - OS: Windows 11
 - Version Version 10.0.22631 Build 22631
 - Godot Version v4.2.2
 - Type simd single 2d v0.6.21

**Comment by Ughuuu** [comment]
Hi, this is the old version of rapier(which is currently on asset store because it still has fluids). Can you try the new version from this repo and see if it still happens?

**Comment by onkeltora** [comment]
> Hi, this is the old version of rapier(which is currently on asset store because it still has fluids). Can you try the new version from this repo and see if it still happens?

This is on latest Release from Git. (simd single 2d v0.6.21)

**Comment by Ughuuu** [comment]
Can you try 7.12?

**Comment by Ughuuu** [comment]
In any case, 1 week passed without update, also as it stands this issue doesn't have clear reproductible steps(or a project attached eg. zipped). You can re-open the issue with those if it still happens.
