### ISSUE TITLE
CharacterBody and large CollisionPolygon cause low framerates/performance

### ISSUE THREAD

**Issue by jjanella** [appsinacup/godot-rapier-physics#149]
**Describe the bug**

A CharacaterBody2D moving towards a CollisionPolygon2D with hundreds of verticies will significantly drop framerates.

**To Reproduce**

Move a CharacterBody at high speed towards a CollisionPolygon2D at a very high speed.

**Expected behavior**

Framerates do not drop, as they do not drop with the default physics engine.

**Environment:**
 - OS: Arch Linux
 - Version v0.6.21
 - Godot Version 4.2.2.stable
 - Type simd

Reproduction is difficult but here is a recording. Watch the speed in the bottom left corner to see that the framerates drop and/or physics frame time increases.

https://github.com/user-attachments/assets/28d918a4-74fa-4b60-b898-9838cbd4b877

**Comment by Ughuuu** [comment]
Can you try with latest pre-release version too?

**Comment by jjanella** [comment]
The latest pre-release doesn't seem to work with my game; however I went back along the single-simd route and found this bug was introduced at v0.6.7, it did not occur in v0.6.6.

**Comment by jjanella** [comment]
This was fixed at or before v0.7.8
