### ISSUE TITLE
Collisions don't work

### ISSUE THREAD

**Issue by jjanella** [appsinacup/godot-rapier-physics#153]
**Describe the bug**

Objects that should don't collide, they pass right through each other

**To Reproduce**

Try to collide two objects

**Expected behavior**

Collision shapes cause collisions

**Environment:**
 - OS: Arch Linux
 - Version [v0.7.14]
 - Godot Version [4.2.2.stable]
 - Type [simd single 2d]

**Example project**

```swift
extends Node2D

func _ready():
	var rb = RigidBody2D.new()
	var rbc = CollisionPolygon2D.new()
	rbc.set_polygon([Vector2(0, 0), Vector2(20, 0), Vector2(20, 20), Vector2(0, 20)]) 
	rb.add_child(rbc)
	add_child(rb)
	rb.position = Vector2(150, 50)

	var sb = StaticBody2D.new()
	var sbc = CollisionPolygon2D.new()
	sbc.set_polygon([Vector2(100, 100), Vector2(200, 100), Vector2(200, 200), Vector2(100, 200)]) 
	sb.add_child(sbc)
	add_child(sb)
```

https://github.com/user-attachments/assets/6f062cac-e5f4-4510-a504-bd18a2dcc42b

**Comment by Ughuuu** [comment]
See if this fixes it:
https://github.com/appsinacup/godot-rapier-physics/releases/tag/v0.7.15

**Comment by jjanella** [comment]
This fixed most issues, however segmented polygons still dont collide. Here is a modified version of the example project.

```swift
extends Node2D

func _ready():
	var rb = RigidBody2D.new()
	var rbc = CollisionPolygon2D.new()
	rbc.set_polygon([Vector2(0, 0), Vector2(20, 0), Vector2(20, 20), Vector2(0, 20)]) 
	rb.add_child(rbc)
	add_child(rb)
	rb.position = Vector2(150, 50)

	var sb = StaticBody2D.new()
	var sbc = CollisionPolygon2D.new()
	sbc.build_mode = CollisionPolygon2D.BUILD_SEGMENTS
	sbc.set_polygon([Vector2(100, 100), Vector2(200, 100), Vector2(200, 200), Vector2(100, 200)]) 
	sb.add_child(sbc)
	add_child(sb)
	rb.position = Vector2(150, 50)
```

**Comment by Ughuuu** [comment]
Check version 0.7.16

**Comment by jjanella** [comment]
Oddly the reproduction I've made for it here is fixed, however in my larger project it's not fixed. Will try reproduce it.

**Comment by jjanella** [comment]
Works on v0.7.18
