### ISSUE TITLE
Area2D not detecting segment-built bodies

### ISSUE THREAD

**Issue by jjanella** [appsinacup/godot-rapier-physics#154]
**Describe the bug**

Area2D does not detecting segment-built bodies with `get_overlapping_bodies()`

**To Reproduce**

Try to use an Area2D to detect an overlapping body that has its collision shape segment-built. I would assume this goes for `get_overlapping_areas()` as well because this has to do with the collision polygon more so than the area, but have not tested it.

**Expected behavior**

`get_overlapping_bodies()` works as intended.

**Environment:**
 - OS: [4.2.2.stable]
 - Version [v0.7.15]
 - Godot Version [4.2.2.stable]
 - Type [simd single 2d]

Very likely related to https://github.com/appsinacup/godot-rapier-physics/issues/153

**Comment by Ughuuu** [comment]
Check latest version and see if its fixed.

**Comment by jjanella** [comment]
Oddly the minimal reproductions for it are fixed, however in my larger project it's not fixed. Will try reproduce it.

**Comment by jjanella** [comment]
Works on v0.7.18
