### ISSUE TITLE
Examples on Fluid2d/Fluid3D setup?

### ISSUE THREAD

**Issue by skalimoi** [appsinacup/godot-rapier-physics#158]
Hi, I'm trying to setup a Fluid3D node but there's not much documentation on it so I'm having some trouble. Do you plan on making documentation available for it?

**Comment by Ughuuu** [comment]
In time I do plan to add to the documentation page. This is going to be the first implementation draft of liquids: https://github.com/appsinacup/godot-rapier-physics/pull/159 after rewrite.

**Comment by Ughuuu** [comment]
Will update the documentation page soon after I make the release with this.

**Comment by Ughuuu** [comment]
Check this page for examples https://godot.rapier.rs/docs/documentation/fluids/

Right now only for 2d there are renderers, for 3d you have to write ur own. If you have good ones I can add them into the plugin too. If not will add with time.

**Comment by Ughuuu** [comment]
Added 3d examples too and a basic renderer, I think this would be enough to get people started.
