### ISSUE TITLE
windows on arm64 support

### ISSUE THREAD

**Issue by gregbug** [appsinacup/godot-rapier-physics#164]
i'm using godot 4.3 in native mode under windows arm64 laptop (snap elite x)
recompiled godot from sources for arm64 and work fine but rapier lib for arm64 under windows is not avaible.
any eta? or can you provide an example on how to recompile for arm64?
thx.

**Comment by Ughuuu** [comment]
Looks like it should be supported(using rust for this project) as a tier 2 target. https://doc.rust-lang.org/nightly/rustc/platform-support.html

Adding it to the build system and will let you know if I get it working. If it works effortlessly I should have it build in 1-2 days.

**Comment by Ughuuu** [comment]
Added here: https://github.com/appsinacup/godot-rapier-physics/pull/165

**Comment by gregbug** [comment]
thanks!

**Comment by Ughuuu** [comment]
Also should be in this release: https://github.com/appsinacup/godot-rapier-physics/releases/tag/v0.7.20
