### ISSUE TITLE
TouchScreenButtons break with Rapier2D enabled

### ISSUE THREAD

**Issue by Robert-K** [appsinacup/godot-rapier-physics#171]
**Describe the bug**

If you enable Rapier 2D physics in Godot Project, TouchScreenButtons register no more touch events.
As soon as I disable the Rapier physics, they start working again.

**To Reproduce**

Add this to your project settings:
```
[physics]
2d/physics_engine="Rapier2D"w
```
Add a TouchScreenButton to any scene. It will not emit any signals or InputEvents on touch.

**Expected behavior**

TouchScreenButtons should be unaffected by Rapier or at least work similarly.

**Environment:**
 - OS: Windows
 - Godot Version: tested with 4.2, 4.3rc1, 4.3dev6
 - Type: simd single 2d

**Example Project:**
[touch-buttons-test.zip](https://github.com/user-attachments/files/16430073/touch-buttons-test.zip)

"Mouse input as touch" is enabled, so this can also be tested using the mouse.
Tapping the button/pressing space will print "Hey!".
If I enable Rapier, it doesn't.

**Comment by Ughuuu** [comment]
The touchscreen button uses shape_collide with no motion, and in rapier the function without motion results in no result, bc it can't put a direction (eg normal results in size 0).
So put a small motion to both of 0.001 (before they also had this, but they both had same motion, so same issue, so now changed to put to one a motion of -0.001, -0.001 and other 0.001, 0.001).
