### ISSUE TITLE
Area Layer issue + Pin Joint inaccuracy/jam

### ISSUE THREAD

**Issue by JonSnowbd** [appsinacup/godot-rapier-physics#174]
**Describe the bug**

Area layer issue:
- Area2D will only use its layer attributes to find objects
- Objects not on a layer, but shares a mask layer with the area's layer, will be falsely detected

Pin joint issue:
- Pin joint does not expose settings for the modified behaviour to have parity with how it works on default physics.

**Environment:**
 - OS: Windows 11
 - Version: latest rapier release.
 - Godot Version: 4.3.beta3
 - Type: simd 2d

**Example project(zip)**

Dont forget to enable Debug->Visible Collision

[rapierrepro.zip](https://github.com/user-attachments/files/16447002/rapierrepro.zip)

**Comment by Ughuuu** [comment]
Pin joint doesn't have indeed softness and bias. There is no way to support them in rapier. Will add more about this at limitations in documentation website.

**Comment by Ughuuu** [comment]
As for rest of issues with Area, have a fix that fixes some part of it, but will need to investigate more all the different use cases and see exactly how to make it match godot behaviour.

**Comment by Ughuuu** [comment]
The pin joint jamming is related to this: https://github.com/dimforge/rapier/issues/692
The body sleeps and then the joint doesnt wake up the body again. For now a workaround is to se the body to never sleep.

**Comment by Ughuuu** [comment]
Can you check again if it's fixed now?

**Comment by Ughuuu** [comment]
Closing as it's now fixed.
