### ISSUE TITLE
If Rigidbody is instantiated near a Staticbody, it's velocity does not get reset after landing

### ISSUE THREAD

**Issue by DragonEngineer** [appsinacup/godot-rapier-physics#180]
**Describe the bug**
If a rigidbody is spawned near (but not overlapping) a staticbody, when that rigidbody lands on the staticbody, the rigidbody's Y velocity continues to increase

**To Reproduce**
1. Open the attached project
2. Run the game, Rigidbody box will spawn like 5 seconds later
3. Notice the debug label shows that the Y velocity keeps increasing even though it landed on a staticbody (Ignore the X velocity because it's moving horizontally by setting position)
4. Go back to the editor
5. Find the "outlet" object and move it higher up
6. Run the game, Rigidbody box will spawn like 5 seconds later
7. Notice the debug label now shows the Y velocity is 0 when landed on a staticbody (intended behaviour)

**Expected behavior**
The Y velocity should be 0 when landed on a staticbody

**Environment:**
- OS: Windows 10
- Version 0.7.18
- Godot Version 4.2.1
- Type SIMD Single 2D
- CPU: AMD Ryzen 7 4800H with Radeon Graphics
- GPU: Nvidia Geforce GTX 1650

**Example project(zip)**
- After downloading, need to put the Rapier (SIMD Single 2D) addons inside the addons folder before opening the project
- You can run "test_level.tscn" to see the bug
- Project file: [FactoryBoxes.zip](https://github.com/user-attachments/files/16495518/FactoryBoxes.zip)

**Comment by DragonEngineer** [comment]
Bugged version: https://streamable.com/8g3xym
Intended version: https://streamable.com/4ls9mm

**Comment by Ughuuu** [comment]
Strange bug, but it appears sometimes the body is moved just above the static body, and it resets velocity, sometimes no. The function with problem is probably move_and_collide. Though that is a high level function. Not 100% sure if it should just collide with the static body or not.
