### ISSUE TITLE
One way collisions doesnt work for RigidBodies

### ISSUE THREAD

**Issue by planner404** [appsinacup/godot-rapier-physics#192]
**Describe the bug**

One way collisions don't work.

**To Reproduce**

Have an AnimateableBody2D with one way checkbox enabled on it's collision shape. Make this body go up and down with PathFollow2D. Put Rigidbody2D object under it. Make sure collision masks and layers can see each other.

**Expected behavior**

Object should've passed through the under of the moving platform since one way collision is on, but it doesn't. Correct behaviour can be seen when switched to default engine.

**Environment:**
 - OS: Windows 10 22H2  (19045)
 - Rapier version 0.7.26, Cross platform deterministic.
 - Godot Version 4.2.2 stable
 - Type Collisions..? (Don't know what this means)

**Example project(zip)**

Here is the project zip with no addons folder.
[rapier-oneway-bug.zip](https://github.com/user-attachments/files/16567357/rapier-oneway-bug.zip)

**Comment by Ughuuu** [comment]
One way collisions for rigidbodies should be fixed now. For character body still no. Re-checking if this issue is fixed(for rigidbodies)
