### ISSUE TITLE
Bug Report: ShapeCast2D Detection Issue

### ISSUE THREAD

**Issue by ismettaha** [appsinacup/godot-rapier-physics#193]
**Describe the bug**

ShapeCast2D is not functioning as expected with CircleShape2D. It shows unpredictable detection behavior during collisions.

**To Reproduce**

Slowly move the 'target position' parameter of the ShapeCast2D, with CircleShape2D, towards a CollisionShape2D beneath it, run force_shapecast_update(). This issue is especially noticeable with small collisions and incremental movements.

**Expected behavior**

ShapeCast2D should reliably trigger whenever it collides with another object. There should not be an large collision intersection area for the detection to occur. This behavior works correctly when using the default engine settings.

**Environment:**
 - OS: Macos Sonoma 14.4.1
 - Version: 0.7.26
 - Godot Version: v4.2.2.stable.offical [15073afe3]
 - Type: Fast Version With Parallel  SIMD Solver

**Example project(zip)**

A project zip file with no add-ons is attached. Please enable 'visible collision shapes' from the debug menu and press space to start the test.
[rapier.zip](https://github.com/user-attachments/files/16571119/rapier.zip)

**Comment by Ughuuu** [comment]
Haven't investigated what causes it, but I was able to reproduce it locally.

**Comment by Ughuuu** [comment]
I kinda have a fix for this. I was basically not computing the unsafe fraction correctly, so I was returning the toi for intersection a bit smaller at all times. Now I am computing the unsafe fraction too and it seems to work well enough. Maybe in some cases it triggers 1 pixel too early. I need to check that maybe it's some epsilon/tolerance issue, but for now this is solved (it used to be even worse at big distances, eg 2000, but now its pretty reliable, detects when even 1 pixel changes).
