### ISSUE TITLE
Pinjoint2d softness property doesn't work

### ISSUE THREAD

**Issue by aahmyu** [appsinacup/godot-rapier-physics#194]
**Describe the bug**

I was looking at the pinjoint 2d and I noticed that the softness doesn't affect the joint at all. Not sure if I'm doing something wrong. The same project works fine in the default engine.

**To Reproduce**

Add steps here
Create a static body, ridid body and pinjoint2. link the bodies to the joint and adjust the softness.  

**Expected behavior**
The softness should affect the ridgid body and make it a bit loose. 

**Environment:**
 - OS: Linux Ubuntu 24.04
 - Godot 4.3 RC 3
 - The fast version
[joints2d.zip](https://github.com/user-attachments/files/16594865/joints2d.zip)

**Example project(zip)**

Please attach a zip with project where issue occurs. Remove the **addons** folder so that the size is less than 25 mb.

**Comment by Ughuuu** [comment]
That is true, right now rapier doesn't have any property for softness in pin joints. There is a matching issue on rapier side, will link it with this one.

**Comment by Ughuuu** [comment]
You can check progress of that task there, basically so far no progress, I just proposed of exposing 2 params that might help with this from per world to per joint.

**Comment by Ughuuu** [comment]
In any case, softness will not be supported same way as it is today. Rapier might have support for this, but it will be 2 params exposed, godot has one param.
This when fixed will add support to remove the softness and add new params for softness (for all joints) https://github.com/godotengine/godot-proposals/issues/10438#issuecomment-2307782398

**Comment by Ughuuu** [comment]
For now updating README, since it seems like the linked issues will take a while to get fixed, and not sure this one is worth keeping opened here.

**Comment by Ughuuu** [comment]
But basically, there are some limitations in rapier, there is currently no way to disable properties that are unused by rapier. I linked a PR that allows rapier to hide those properties, so at least it's clear that rapier does not implement them.
Also, on rapier side there is an issue that **might** help with this, but in another form, it won't be softness for sure, it will be **damping_ratio** and **natural_frequency**, but you will be able to do almost same thing with those.

**Comment by Ughuuu** [comment]
Tracked by: https://github.com/appsinacup/godot-rapier-physics/issues/231
