### ISSUE TITLE
Using CollisionShape2D in AnimationPlayer will report an error.

### ISSUE THREAD

**Issue by PlayerYF** [appsinacup/godot-rapier-physics#195]
Describe the bug

Using the CollisionShape2D in the AnimationPlayer will report an error and the determination will no longer take effect.

To Reproduce

Add steps here
Adding Steps Adding CollisionShape2D.position Keyframes AnimationPlayer

E 0:00:03:0613   godot_core::private::report_call_error: godot-rust function call failed: RapierPhysicsServer2D::step()
    Reason: [panic]
  assertion `left != right` failed
    left: 7
   right: 7
  <C++ 源文件>      C:\Users\runneradmin\.cargo\git\checkouts\gdext-76630c89719e160c\a20bb85\godot-core\src\private.rs:318 @ godot_core::private::report_call_error()

Expected behavior

Environment:

OS: Window10
Godot 4.3 RC 3
The fast version godot-rapier-2d-single-simd-parallel 0.7.26

Example project(zip)

Please attach a zip with project where issue occurs. Remove the addons folder so that the size is less than 25 mb.

Run after installing the plugin
[TestRapier.zip](https://github.com/user-attachments/files/16607389/TestRapier.zip)

**Comment by Ughuuu** [comment]
This error is still present and not yet fixed. Reopening.

**Comment by Ughuuu** [comment]
Seems to be related to scaling the area with -1. Investigating why.
