### ISSUE TITLE
Questions about determinism

### ISSUE THREAD

**Issue by nicolagianelli** [appsinacup/godot-rapier-physics#203]
Hello, I start by thanking you for this addon.
I saw from the docs that there is a deterministic version but it has few limitations, scripting and user inputs, these limitations depends on the usage of floats?
Is it a problem even if I work with few decimals? How do you suggest to get user inputs maintaining determinism?
Last question, is there a way to manual simulate physics? I'm working on a multiplayer game where rollbacks happens so it would be good to manual simulate physics.

Thank you!

**Comment by Ughuuu** [comment]
For manual simulation, there is an issue in Godot. I would wait for that or push for that to be solved first. https://github.com/godotengine/godot/pull/76462

As for others, I would say you should test each thing and see if it's deterministic or not(cross platform). I have not tested yet thoroughly cross platform determinism, so can't comment much on that. First Godot will need to have support for some stuff.

I could add manual stepping, but seeing as how Godot is close to add that, I will probably wait for that PR to stabilize.

**Comment by nicolagianelli** [comment]
> For manual simulation, there is an issue in Godot. I would wait for that or push for that to be solved first. [godotengine/godot#76462](https://github.com/godotengine/godot/pull/76462)
> 
> As for others, I would say you should test each thing and see if it's deterministic or not(cross platform). I have not tested yet thoroughly cross platform determinism, so can't comment much on that. First Godot will need to have support for some stuff.
> 
> I could add manual stepping, but seeing as how Godot is close to add that, I will probably wait for that PR to stabilize.

Ok I'll test it, for the manual stepping I saw that pull request months ago... Let's see if it will be merged anytime soon...
