### ISSUE TITLE
Rapier Physics 2D - Fast Version with Parallel SIMD Solver is 404ing

### ISSUE THREAD

**Issue by GeminiSquishGames** [appsinacup/godot-rapier-physics#207]
Can't seem to download it since it's 404.

**Comment by Ughuuu** [comment]
Thanks for letting me know, fixed. Have to change godot assets page every time a new release appears, and made a typo this time.

**Comment by GeminiSquishGames** [comment]
Gave it a while but it's still 404. Maybe a little longer. I can update from release but will check later also.

**Comment by Ughuuu** [comment]
Fixed now. Thanks again for reporting it.
