### ISSUE TITLE
ShapeCast3D Returning incorrect collision point

### ISSUE THREAD

**Issue by Peter229** [appsinacup/godot-rapier-physics#212]
**Describe the bug**

When using a ShapeCast3D the collision point is deeper than the surface I am casting against.

**To Reproduce**

Add a ShapeCast3D going straight down with a cylinder shape with height of 0.1, then play with Debug Visible Collision Shapes

**Expected behavior**

Expect to see the cylinder shape sat perfectly on top of the surface like this (This is using default Godot physics in 4.3):
![image](https://github.com/user-attachments/assets/946434f6-23a7-4c40-8fc2-2f497949ebbe)

Instead it appears like this:
![image](https://github.com/user-attachments/assets/abec4f39-89d4-4ea0-a2b3-a4e1032da109)

**Environment:**
 - OS: Windows
 - Version 0.8.0
 - Godot Version 4.3
 - Type SIMD 3D

**Comment by Ughuuu** [comment]
There is a similar issue for ShapeCast2D. Probably related.

**Comment by Ughuuu** [comment]
This is related to the cylinder shape not working correctly.
