### ISSUE TITLE
Godot Physics 2D Feature Parity

### ISSUE THREAD

**Issue by Ughuuu** [appsinacup/godot-rapier-physics#213]
Shapes:

- https://github.com/appsinacup/godot-rapier-physics/issues/220

**Comment by Ughuuu** [comment]
Just 1 so no need for this issue holder

**Comment by naturally-intelligent** [comment]
On the Implementation page it says Capsule shape not available.

Is there Capsule shape or plans to add one?

**Comment by Ughuuu** [comment]
<img width="303" alt="image" src="https://github.com/user-attachments/assets/59ae8cb3-d893-44d1-9078-6a34e8ee3cc2" />
