### ISSUE TITLE
Area2D does not detect overlaps in web builds

### ISSUE THREAD

**Issue by JonathanKohlhas** [appsinacup/godot-rapier-physics#225]
**Describe the bug**

All instances of Area2D fail to detect any overlaps and enter/exit events when running in Web.

**To Reproduce**

- Create Project
- Create Area2D and any other CollisionObject2D with CollisionShapes etc.
- use any of the ovelap checking function (get_overlapping_areas, get_overlapping_bodies, on_body_entered, ...)
- build in editor => overlap is detected
- build for web => overlap is not detected

**Expected behavior**

Overlap should always be detected

**Environment:**
 - OS: Mac (running in browser, tested both Firefox and Chrome)
 - Version: 0.8.0
 - Godot Version: 4.3
 - Type: 2D with Cross Platform Deterministic

**Example project(zip)**

Example Project is without Rapier2D otherwise the zip is too big
[new-game-project.zip](https://github.com/user-attachments/files/16728388/new-game-project.zip)

**Comment by Ughuuu** [comment]
Strange that this only occurs on the web. I'll give it a try see if it happens for me too.

**Comment by Ughuuu** [comment]
My guess is that it's possible the godot-rust plugin doesn't register the plugin at the right time? Or something else is wrong with events/callables? I'll need to check more in depth, add more logs, etc. But it is a very weird bug indeed.

**Comment by skyne98** [comment]
Can confirm, also happens to our project, seems to be Area2D related 👍🏻

**Comment by skyne98** [comment]
Will have to postpone the web build by a bit, and otherwise the extension is really cool, thanks for the remarkable work!

**Comment by Ughuuu** [comment]
Currently fixing other bugs and implementing other things but this is very high priority.

**Comment by Ughuuu** [comment]
Seems to be caused by his: https://github.com/dimforge/rapier/issues/737

Simply adding the default trait impl makes it work. The default for web was to drop intersections, while for desktop was to not drop them. Making both platforms not drop intersections make it work.
