### ISSUE TITLE
Compilation error during the export of iOS project

### ISSUE THREAD

**Issue by ihoshiki** [appsinacup/godot-rapier-physics#227]
**Describe the bug**

Much much appreciated your effort to provide a solid physic solution to Godot 4.3.  Recently, I tried to switch the Physic 2D to Rapier2D in my Godot project.  There are iOS build exception with Rapier2D

Before I switched to Rapier2D, the build was successful and I could be able to test the game in the mobile device.  After my Godot project switched to Rapier2D, the export was not successful.  The compiler reported that the framework **'libgodot_rapier.ios'** not found.

**To Reproduce**

1. Create a Godot project, in the project create a main scene with/without any nodes.
2. Download and Install Rapier2D (Fast version).  
3. At "Tab Menu > Project >  Project Setting ..." , switch the Physic 2D engine to Rapier2D.
4. At "Tab Menu > Project > Export ..." ,  add iOS Preset.
5. In the "Export Page", set the following values, e.g. :
 "Export Path": "/users/tester/documents/ios-export/ios-export.ipa"
 "App Store Team ID": e.g. "12345ABC"
 "Bundle Identifier": e.g. "com.company.test"
 "arm64": ON
 "Import ETC2 ASTC": Enabled
<img width="1077" alt="Screenshot 2024-08-25 at 23 25 55" src="https://github.com/user-attachments/assets/1993d519-850d-480f-bc22-f5f3071ccd59">
6. In the Export Page, Press "Export All..." Button.
7. Exporting failed because of the framework 'libgodot_rapier.ios' not found.
<img width="740" alt="Screenshot 2024-08-25 at 23 18 13" src="https://github.com/user-attachments/assets/7ff15668-4e76-49c7-93bb-6ed9b9b86993">
<img width="917" alt="Screenshot 2024-08-25 at 23 19 35" src="https://github.com/user-attachments/assets/d7ef3bdc-e76d-4a14-aebe-f63b1ebec188">

**Expected behavior**

The build of iOS is expected to be success without critical error.  The exported iOS project could be opened and build with Xcode.  The game could be played by the iOS simulator in the Xcode environment.

P.S. I enjoyed the Rapier physic.  Thanks for making my day :)

**Environment:**
 - OS: macOS Sonoma 14.6.1 (M2 Chips)
 - Version: 0.8.0
 - Godot Version: v4.3.stable.mono
 - Type: simd single 2d
 - Xcode: 15.4

**Example project(zip)**
[sample godot project.zip](https://github.com/user-attachments/files/16742187/sample.godot.project.zip)

Please attach a zip with project where issue occurs. Remove the **addons** folder so that the size is less than 25 mb.

**Comment by Ughuuu** [comment]
Interesting, haven't tested this much I'll admit. Probably a configuration issue. Will check and update.
