### ISSUE TITLE
Web export needs implemented

### ISSUE THREAD

**Issue by Ughuuu** [appsinacup/godot-rapier-physics#23]
Maybe related to this?

https://github.com/godotengine/godot/issues/82865

Try out when that is fixed.

**Comment by souvikinator** [comment]
Hi! Any update on this?

**Comment by Ughuuu** [comment]
From what i see the linked issue is still open. So probably still wont work

**Comment by Ughuuu** [comment]
Actually the simd-stable also doesnt work with web. Disabled that in this PR https://github.com/appsinacup/godot-rapier-2d/pull/46 to see if it works. Will update if it works. Am investigating still tho.

**Comment by Ughuuu** [comment]
Small update on this. Make it start at all. Before it didn't want to load the dll, now it loads it, but at the step function it throws in the browser:
```
Aborted(Assertion failed: bad function pointer type - dynCall function not found for sig 'vijiiiiiiiiiiii')
	$world_step
	$_ZN13RapierSpace2D4stepEf
```

I am building locally with emscripten 3.1.56, but will try with other version to see if it works with any. Godot GDExtension uses 3.1.45, with that it doesn't load at all.

**Comment by Ughuuu** [comment]
By removing the call to step from rapier code, it works. So the problem is the world_step function and what it does most likely.
I think first I would need to keep on removing stuff from step and see what causes it (my guess is it's the callbacks or their signature).

**Comment by Ughuuu** [comment]
Ok, on this, I looked at what godot-rust is doing, and they have web exports working. So I think migrating this addon to be a godot-rust gdext would give us web exports.

Issue link where they describe how they added support for building web exports:
https://github.com/godot-rust/gdext/issues/438

**Comment by Ughuuu** [comment]
Follow this for info https://github.com/godot-rust/gdext/issues/438

**Comment by Ughuuu** [comment]
Ok, now that I rewrote it to rust, I'll see if it will work. Also 4.3 did some changes to help with this, will try to see if anything changed on this issue.

**Comment by Ughuuu** [comment]
Removing it from issues as it is in readme as limitation. Better to not track it in issues also.
