### ISSUE TITLE
PinJoint2d not using softness, no elasticity.

### ISSUE THREAD

**Issue by GeminiSquishGames** [appsinacup/godot-rapier-physics#230]
**Describe the bug**

The PinJoint node is lacking softness that it's Godot counterpart has. 

**To Reproduce**

Make two rigidbody2d nodes and connect them to a pinjoint2d, set the softness all the way up and observe how they are sill tightly bound and have no elastic give between them. no change from 0.0 softness.

**Expected behavior**

I expect them to act more like elastic keeping them together rather than a solid rod when softness is not 0.0, and have the same ammount of elastic as Godot's version. solid at 0.0 is fine and expected. 

**Environment:**
Windows Godot 4.3

**Example project(zip)**

Should be simple enough to do quickly without, but I will if you cannot reproduce.

**Comment by Ughuuu** [comment]
Related to this: https://github.com/appsinacup/godot-rapier-physics/issues/194
Rapier doesn't have softness on pin joints right now. I added in readme at limitations chapter. Read the linked Issue to see more. Basically when the thing needed to expose softness (in some form) in rapier enters, then godot-rapier can use that for softness (kinda)

**Comment by Ughuuu** [comment]
Tracked by: https://github.com/appsinacup/godot-rapier-physics/issues/231

**Comment by Ughuuu** [comment]
Np. I know, I also kind of want/like the softness of pin joint more, and also the fact that pin joint has limits is better. I used the project settings and got good results, but y it does change the result of all joints, so not good option to do individual softness.

**Comment by GeminiSquishGames** [comment]
I looked at your request issue on the main rapier repo and thought of a few things. The softness goes from 0 to 16 for me... is that not right? Godot's PinJoint2D also has angular clamping, but I think that works, maybe, as well as a motor for automated locomotion which seems to turn in the GodotRapier addon but not so much the same as in Godot physics but I have to test again when I have time to describe the differences better, and there is a bias between the two objects using the joint, just incase that's doable and to keep it as close as possible of a replacement. It's hard for me to tell what might be working right even in Godot's physics case as things seem off to me compared to Unity's joints. Surely Unity does everything right... right? :P

**Comment by Ughuuu** [comment]
Godot Physics exposes all settings and as I said there is no way to hide them.
Rapier doesn't do softness. It does not. The softness in Godot is between 0 and 16, yes.
Rapier has other settings that do, lets call it, "joint takes more to stabilise" setting. This is not the same as "softness", as you noted. So in this case, Rapier has 1 setting, and Godot has another setting.
That's what the proposal I opened in Godot Proposals is about, it's about hiding things that Rapier doesn't do (eg. bias for eg. also) from the inspector so people aren't confused. And it's also about adding new properties that Godot does not have at all (one example is collision shapes with rounded corners, thats something Godot does not have at all).

What Unity has doesn't have much to do here, basically the whole purpose of Rapier is to expose the settings of Rapier Lib. That's it. If there are matches with Godot, then expose them as they are. If not, then that's it. We need to accept that limitation and see what we can do as a workaround.

**Comment by GeminiSquishGames** [comment]
Ah, so the angular clamping and motor are a fluke and will eventually go away you mean? I'll make a note of that. What I mean about Unity is just what I'm used to vs what Godot does out of the box personally, so it's hard for me to tell since they are, all three things, different creatures. I really can't tell if Rapier does anything right, just that I can use it to do what I want with minimal effort compared to Godot default. The thing about Unity was just what I'm used to, but I want it in a raster renderer not pretend 2D in a 3D space, so Godot is my choice, but it's default is wonkier than wonky.

The project settings work well for now actually, and may just have to work for a while, so thank you for your help and patience with me. I sometimes have a hard time being succinct and trying to get all of my thoughts out properly and questions asked well to get answers. I still don't really understand all of the Rapier settings so I will try using it's own documentation.

**Comment by Ughuuu** [comment]
No, angular limits and motors are there to stay (for pin joint) And for all joints to come (after the change, I think at least). Best to see is what rapier has to offer I think for joints for a sneak peak of what it has: https://rapier.rs/docs/user_guides/rust/joints

I want to expose all that rapier has to offer for joints for all joints godot has. So the softness will come for all joints, the angular limits probably also for all joints? I'll see what rapier has and map it to the nodes.

Right now it's hard to know what works and what doesn't, but this is because Godot doesn't offer the option to do so. So only thing I can do now is no-op in such a case.

Hopefuly this will be impl in godot 4.4 (or later, though I really hope 4.4)
