### ISSUE TITLE
RigidBody3D does not unlock when lock_rotation set to false

### ISSUE THREAD

**Issue by Teufelauto** [appsinacup/godot-rapier-physics#245]
**Describe the bug**

'lock_rotation = false' does not free the RigidBody3D to rotate freely. It can be rotated by transform.basis, but when dropped, the body does not rotate. The check-box in the Inspector behaves correctly, but the body rotation remains locked. 

**To Reproduce**

For a RigidBody3D, set lock_rotation = true in the Inspector, or by code. Setting lock_rotation = false will not unlock the rotation.

I have provided a test project below that requires the Addon folder with Rapier installed.

1. Run the project. I must note that if the Godot Editor is moved to my second screen, running the project will cause the cube not to reset to the starting position. IDK what to do with that info.
1a. The left cube is frozen, showing a separate bug relating to starting frozen identified elsewhere. Please disregard it.
1b. The right cube will fall when the app runs, and come to rest normally on one side.
2. Clicking 'Drop Cube' will return the cube to the start position and drop it again at a random starting rotation.
3. Clicking 'Lock Rotation' calls function that causes lock_rotation = true.
4. Clicking 'Drop Cube' sets lock_rotation = false, returns the cube to its starting location, randomly rotates it, and lets it fall.
5. Observe the cube does not rotate onto a face after it hits the ground, remaining in the same orientation as when it was released, balanced on a vertex.
6. Commenting out 'lock_rotation = false', shows transform.basis still allows rotation to be manually set while locked.

**Expected behavior**

Setting lock_rotation = false should allow the RigidBody to rotate due to the effects of gravity, impacts, or other processes.

**Environment:**
 - OS: Windows
 - Version v0.8.2 and v0.8.4
 - Godot Version v4.3
 - Type godot-rapier-3d-single-simd-parallel

**Example project(zip)**

[rapier_lock_rotation_test.zip](https://github.com/user-attachments/files/16827161/rapier_lock_rotation_test.zip)

**Comment by Ughuuu** [comment]
Interestingly, it seems the transform is not set and the bodies don't move back again. My initial guess is the freeze state maybe does something to the shapes that resets them and transform is not applied.

**Comment by Ughuuu** [comment]
As for the lock_rotation, I forgot to update it, fixed that. The position not updating is still not fixed, so leaving this open.
The fix will enter in 0.8.6(for lock_rotation)

**Comment by Ughuuu** [comment]
Just partially fixed, got closed automatically by the PR bc it found the work "fix"
