### ISSUE TITLE
Docs website is out of date with current release

### ISSUE THREAD

**Issue by DanielKinsman** [appsinacup/godot-rapier-physics#246]
Particularly the [serialisation stuff](https://godot.rapier.rs/docs/documentation/deserialization), it appears _all_ the import methods were removed along with the binary exports.

Incidentally, any chance they coming back? I am playing around with determinstic network stuff and being able to get a quick hash of the space state without all the mess of json would be nice. It's a fun experiment but probably a lost cause though so don't put any real effort into it just on my behalf.

**Comment by Ughuuu** [comment]
Hi, the import stuff were never implemented. I have a pr that will add them, i did add the docs for them since i added for serialize, also added for deserialise.

You can see here at bottom of page progress, deserialisation is still missing: https://godot.rapier.rs/docs/progress

**Comment by Ughuuu** [comment]
Will add a small warning at the deserialize page to say it's not yet done.

**Comment by Ughuuu** [comment]
Updated docs page:
<img width="782" alt="image" src="https://github.com/user-attachments/assets/729bbfd5-ab40-4ace-beea-04fd3ed3d8e8">
