### ISSUE TITLE
Collisions/contacts are not detected and/or accessible to scripts

### ISSUE THREAD

**Issue by werner291** [appsinacup/godot-rapier-physics#250]
**Describe the bug**

On rare occasions, the `body_entered` signal is not triggered when collisions occur. The bodies actually collide as they are supposed to, so it is not a tunneling issue.

**To Reproduce**

The bug is inconsistent and hard to reproduce. The attached project forces the shapes to follow a trace of a known instance where the bug occurs (it releases the ball 5 frames before impact, so the physics engine should be fully in control there)

in the following video, notice how the first bounce off the paddle causes output on the console, but not the second:
https://github.com/user-attachments/assets/55400bb5-97c1-4d66-a6ea-a0c1ead3eee9

Perhaps the following details are relevant, perhaps they are not:
- The ball has cast-shape CCD enabled
- The paddle has a polygon shape

**Expected behavior**

A collision should always consistently trigger some or the other signal that my script can respond to. "body_entered" is typically recommended for this sort of thing.

**Environment:**
 - OS: NixOS Ynstable
 - Godot Version: 4.3
 - Type: SIMD 2D (plugin 0.8.4

**Example project(zip)**

[Breakout (copy).tar.gz](https://github.com/user-attachments/files/16919145/Breakout.copy.tar.gz)

**Comment by Ughuuu** [comment]
Seems like some events are dropped because the distance of collision is positive in some cases. Need to investigate why.
