### ISSUE TITLE
Inaccurate Cylinder3D Shape

### ISSUE THREAD

**Issue by jacob-herrera** [appsinacup/godot-rapier-physics#253]
**Describe the bug**
When using the Rapier3D physics engine, the Cylinder3DShape does not match the expected cylinder shape. The issue with the cylinder only applies to the flat part of the cylinder. The round part of the cylinder is accurate.

**To Reproduce**
Collide with the top or bottom of a Rigidbody3D/Staticbody3D/Characterbody3D that has a Cylinder3DShape as it's CollisionShape3D. The collision is always less than the expected size causing a sinking appearance.
I was able to reproduce this on the following versions:
v0.8.2 - Godot 4.3
v0.8.0 - Godot 4.3
v0.7.23 - Godot 4.2.1
v0.7.18 - Godot 4.2.1

- Create a Rigidbody3D.
- Give the Rigidbody3D a CollisionShape3D with a Cylinder3DShape as it's shape.
- Provide a StaticBody3D underneath the Rigidbody3D for it to land on.
- Play the scene: the cylinder will sink past its expected bounds then stop partway in the floor.

**Expected behavior**
The collision should line up with the Godot collision previews and have size/bounds parity with the default collision cylinder size.

**Environment:**
 - OS: Windows 11
 - Version: v0.8.4
 - Godot Version: 4.3
 - Type: cross platform determinism

**Example project(zip)**
[rapier_cylinder_issue.zip](https://github.com/user-attachments/files/16957510/rapier_cylinder_issue.zip)
(Press space to re-run the simulation)

https://github.com/user-attachments/assets/7d6fb923-ecb9-4ed2-85df-6a8c151b8a90

**Comment by jacob-herrera** [comment]
This might be the same issue as #212.

**Comment by Ughuuu** [comment]
Seems. I was doing for whatever reason:
`physics_engine.shape_create_cylinder((self.height / 2.0) - self.radius, self.radius)`
