### ISSUE TITLE
Question about circle getting stuck in small polygons

### ISSUE THREAD

**Issue by beatrixwashere** [appsinacup/godot-rapier-physics#256]
**Describe the bug**

i (and a couple other people) have been experiencing rigidbodies clipping into collisionshapes even with ccd enabled. the rigidbody has cast shape ccd, and the max ccd substep is set to 128, but nothing changes. i believe this is an oversight on my part, but i'm not sure what exactly went wrong.

**To Reproduce**

1) make a collisionshape for the ground
2) make a rigidbody with a script to control it
3) approach the collisionshape at a high velocity
4) the rigidbody will clip into the collisionshape, losing speed or even getting stuck completely

**Expected behavior**

the expectation was for the rigidbody to detect the collision properly, and stop before the collisionshape rather than get stuck inside it.

**Environment:**
 - OS: linux (& windows)
 - Version: latest
 - Godot Version: 4.3
 - Type: cross platform deterministic 2d

**Example project(zip)**

attached; use arrow keys to move and press x to set the y velocity to a high value
[rapiertest.zip](https://github.com/user-attachments/files/17019455/rapiertest.zip)

**Comment by Ughuuu** [comment]
Tested this, not sure if it's related to ccd actually. What happens is the body moves, it does collide (if it has ccd or not doesnt make much of a difference). Then it should get unstuck:
<img width="387" alt="image" src="https://github.com/user-attachments/assets/a989b106-6118-4003-a1e1-209ff0e8e112">
Problem is it gets stuck between two polygons. Related read: https://box2d.org/posts/2020/04/stuck-inside/

**Comment by Ughuuu** [comment]
Note: The author is using polygon with Solids, but if he were to use Segments instead, this would not happen. However, downside would be that object could cross inside the polygon(unless the object uses ccd).

**Comment by Ughuuu** [comment]
Another thing that might help here is to set a radius on the static polygon of 1 pixel.
`RapierPhysicsServer2D.body_set_extra_param(self.get_rid(), 0, 1.0)`

This way it might not get stuck as much.

**Comment by Ughuuu** [comment]
Added some docs on this here: http://localhost:3000/docs/documentation/rigidbodies#shapes-getting-stuck-inside
