### ISSUE TITLE
`RigidBody2D` cannot move in editor

### ISSUE THREAD

**Issue by steelywing** [appsinacup/godot-rapier-physics#257]
**Describe the bug**

After enable Rapier2D, the `RigidBody2D` node (not `CollisionShape2D`) in editor cannot move

**To Reproduce**

Move the `RigidBody2D` node in editor

**Expected behavior**

Can move

**Environment:**
 - OS: [e.g. Windows]
 - Version 0.8.4
 - Godot Version 4.3
 - Type single-enhanced-determinism

**Example project(zip)**

Please attach a zip with project where issue occurs. Remove the **addons** folder so that the size is less than 25 mb.

**Comment by sccaeleo** [comment]
Having the same issue. When trying to move a rigidbody in the editor, the rigidbody snaps back to the original position. The rigidbodies are in their right position when the game is run. When using Godot's physics engine, the rigidbodies can move fine.

Windows
Version 0.8.4
Godot 4.3
Fast Version 2D
[rapierissuedemo.zip](https://github.com/user-attachments/files/17031969/rapierissuedemo.zip)

**Comment by Ughuuu** [comment]
This is really strange, and to my knowledge didn't happen before 4.3.

**Comment by Ughuuu** [comment]
Seems like godot calls into rapier physics with the same position. Possibly a sync issue? Note that it doesn't always happen.
Trying to see if i can replicate issue in jolt also.

**Comment by Ughuuu** [comment]
Opened this issue on Godot side just in case someone might have some insight:

https://github.com/godotengine/godot/issues/97162

**Comment by Ughuuu** [comment]
3d issue https://github.com/appsinacup/godot-rapier-physics/issues/251

**Comment by Ughuuu** [comment]
> Opened this issue on Godot side just in case someone might have some insight:
> 
> [godotengine/godot#97162](https://github.com/godotengine/godot/issues/97162)

No insight from Godot team on this. Will need to investigate on my own why it happens.

**Comment by larspet** [comment]
So I noticed that if you for example print something in `RigidBody2D::_body_state_changed()`, it will be printed 60 times per second, even while just in the editor (and without moving the `RigidBody2D`).

However, this does not happen when using the default Godot physics. With the default Godot server, the prints will only start showing after the game is actually launched.

Looking further into this, `GodotPhysicsServer2D` will check if it's currently `active` in both `step()` and `flush_queries()`. Rapier physics only seems to check for this in `step()` (specifically in the server implementation class), unless I'm missing something?

So maybe adding a check for `active` in `flush_queries()` could solve this problem? If anything, it would at least make it function more like the default physics server.

**Comment by Ughuuu** [comment]
Nice catch, will try see if it fixes it.
