### ISSUE TITLE
Area2D don't collide in web exports

### ISSUE THREAD

**Issue by LifeHckr** [appsinacup/godot-rapier-physics#260]
When web exporting area2d no longer collide. or body_entered and related signals no longer emit.

Add a CharacterBody2D and an Area2D, connect the Area2D body_entered signal through the editor to a piece of code. Works fine on preview, but on web export Area2D collisions no longer work.

In the sample project there is an area2d below the player, which, on collision should change the text.

**Environment:**
 - OS: Windows
 - Version: latest
 - Godot Version: 4.3
 - Type: fast

**Example project(zip)**
[godottester.zip](https://github.com/user-attachments/files/17180213/godottester.zip)

**Comment by Ughuuu** [comment]
This was fixed on latest master, just a new version/release wasn't yet made.

**Comment by Ughuuu** [comment]
Will make a release soon, re-open if it happens in that too.
