### ISSUE TITLE
Enabling Rapier disables ability to place or move any nodes in Godot 4.3

### ISSUE THREAD

**Issue by kyle-wendling** [appsinacup/godot-rapier-physics#263]
**Describe the bug**

Add description here

**To Reproduce**

- Run latest Godot stable on mac, 4.3, create a few Rigidbody2Ds in 2d, enable Rapier 2d in project settings.
- Select an object, try to move it, most wont move or have weird buggy movement behavior when dragged with the mouse. 
- 
Most Rigidbody2D nodes cannot be moved in the editor, those that can 'move' with 'q' and dragging are buggy. There was a previous fix to 8.4 that was supposed to address this bug, but unfortunately the bug is still very much present, making Rapier basically unuseable in godot sadly.

**Expected behavior**

Nodes are able to be moved around in the editor per normal, the same as if GodotPhysics was selected.

Bug behavior for any 2d project if Rapier enabled.

**Environment:**
 - OS: Mac M1
 - Version 
 - Godot Version 4.3
 - Type [e.g. simd single 2d]

I would love to be able to try out Rapier, I've been enabling it, reloading the project, disabling it, moving an object, reloading over and over to test it out, but this just isn't viable, would love to be able to actually use the engine.

**Comment by Ughuuu** [comment]
Fixed in 0.8.5

**Comment by kyle-wendling** [comment]
awesome! working well, thank you!


https://github.com/user-attachments/assets/782a27df-d6ba-4a38-a18e-2515a04dfdde
