### ISSUE TITLE
version 0.8.5 missing script field in .cfg, updater having trouble deleting on windows 10.

### ISSUE THREAD

**Issue by GeminiSquishGames** [appsinacup/godot-rapier-physics#264]
The new version is missing the script field. Also, the updater runs into issues deleting old files on Windows 10. It brings up the win dialog saying the files are still open and it wants to close them before continuing. I just cancel them but I dunno if it's messing up the process or not.

**Comment by Ughuuu** [comment]
No more updater, deleted it. It doesnt work on windows anyway. Instead use some package manager tool dor godot addons.

**Comment by Ughuuu** [comment]
Do a clean install again(eg delete old one and install again)
