### ISSUE TITLE
Disabling and Re-enabling CollisionShape2Ds is Broken

### ISSUE THREAD

**Issue by jmengenge** [appsinacup/godot-rapier-physics#271]
**Describe the bug**

Transforms of collision shapes that have been disabled are ignored

**To Reproduce**

If at any point a CollisionShape2D is set to "disabled=true" then its local position will be totally ignored for all future collisions if it is re-enabled

**Expected behavior**

It should simply keep the same transform

**Environment:**
 - OS: MacOS
 - Version: 12.7.6
 - Godot Version: 4.3
 - Type: godot-rapier-2d-single-simd-parallel

**Example project(zip)**
[distancetest.zip](https://github.com/user-attachments/files/17274253/distancetest.zip)

**Comment by Ughuuu** [comment]
Looks like it was reusing old shape after re-activating it. Have a possible fix I will try to implement.
