### ISSUE TITLE
Removing collision does not update Area2D

### ISSUE THREAD

**Issue by Changryy** [appsinacup/godot-rapier-physics#290]
**Describe the bug**

If you remove a collision shape that is a child of an Area2D while that collision shape is overlapping with other bodies, the Area2D will keep reporting that those bodies are inside it.

**To Reproduce**

1. Add an Area2D with a collision shape or polygon
2. Add any type of body and make sure it overlaps with the area
3. During runtime remove the collision shape of the Area2D. This can be done by either `area.remove_child(collider)`, `collider.queue_free()` or `collider.disabled = true`
4. Area is still overlapping with the body despite having no collision shape

**Expected behavior**

When a CollisionShape2D or CollisionPolygon2D is disabled or removed from an Area2D the bodies that were inside that collision shape should no longer be in the array returned by `get_overlapping_bodies()`. For each body that was previously inside said collision shape the area should emit the `body_exited` signal. This of course does not apply if the area is still overlapping with those bodies through a different collision shape.

**Environment:**
 - OS: Windows 11
 - Version: 0.8.8
 - Godot Version: 4.3
 - Type: simd single 2d

**Example project(zip)**
[AreaBug.zip](https://github.com/user-attachments/files/17463901/AreaBug.zip)

**Comment by Ughuuu** [comment]
The event is called on rapier side, but it looks like im not updating state correctly in the wrapper.
