### ISSUE TITLE
Point Gravity not working.

### ISSUE THREAD

**Issue by Galllaa** [appsinacup/godot-rapier-physics#323]
**Describe the bug**

If a body collides with the gravity point i should be pulled to the point but instead it always pushes it to the left. Last time when I checked it was on the 0.6 version and it worked as intended.

**To Reproduce**

Add Area2D with collision
In Area2D turn On the Gravity/ SpaceOverride - Replace
Throw / Spawn a Rigibody2D over the Areas Collision Box

**Expected behavior**
The RigidBody2D should be pulled to the center of the Area2D.

**Environment:**
 - OS: [Windows]
 - Version: [ latest]
 - Godot Version: [v4.3]
 - Type: [simd single 2d]

**Example project(zip)**
No Need for example project ( Video Instead)
https://github.com/user-attachments/assets/179fe929-134d-4b35-9a96-7ea8afe6f8cf

**Comment by Galllaa** [comment]
It works. My mistake you can delete this issue.

**Comment by Ughuuu** [comment]
What was the issue? Why did it not go inside the gravity point?

**Comment by Galllaa** [comment]
The Area2D was not there where the collision box was. The Area2d was in the
uper left corner thats why it was pushing it in that direction.

**Comment by Ughuuu** [comment]
I see. Thanks. No worries about opening this, no harm.
