### ISSUE TITLE
One way collision is reversed in TileMap physics layers

### ISSUE THREAD

**Issue by NilOmniscient** [appsinacup/godot-rapier-physics#324]
**Describe the bug**

When using Rapier 2D, TileMap physics layers, one way collision appears reversed from default Godot

**To Reproduce**

Create a godot project, import rapier 2d.
Create a tilemap, add a physics layer, and paint a one-way collision onto a tile. 
Import a character, and run the scene. 
Attempt to pass through the tile from bottom, attempt to stand on tile from top. 

**Expected behavior**

Expected: Tile physics should block character from top, but not from sides/bottom

**Environment:**
 - OS: Windows
 - Version: latest
 - Godot Version: 4.3
 - Type: simd 2d

**Example project(zip)**

[phystest.zip](https://github.com/user-attachments/files/18219273/phystest.zip)

Arrow Keys to move, Space to jump.

**Comment by popcar2** [comment]
Can confirm that it's not just tilemap one-way collisions, but also every one-way collisionshape2D is set to the opposite direction as Godot does it :)

**Comment by Ughuuu** [comment]
Looks this only happens with character body node, not with rigidbody node.

**Comment by Hymenium** [comment]
I am currently experiencing this issue (using v 0.8.8 in Godot v4.3 and 4.4), do you know when the fix be available in the asset library? Thank you!

**Comment by Ughuuu** [comment]
I could deploy it to asset lib too, until then u can use the latest master build.

**Comment by Hymenium** [comment]
> I could deploy it to asset lib too, until then u can use the latest master build.

Where can I find this?  I tried putting version="0.8.9" flavour="godot-rapier-2d-single-simd-parallel" in my add-ons folder but this does not change anything.

**Comment by Hymenium** [comment]
It seems the 'one way margin' parameter is not considered in Rapier2D, or it is not the same as the default Godot engine. For the Godot engine it seems to change the size of the collision shape in the direction of the one way collision.

**Comment by Ughuuu** [comment]
Possible, make another issue with this info then.

**Comment by elvisish** [comment]
i'm still getting upside-down one-way collisions with the Asset Lib version, has it not been updated yet?
