### ISSUE TITLE
Rigidbody 2D with no damp still slows down

### ISSUE THREAD

**Issue by GeminiSquishGames** [appsinacup/godot-rapier-physics#81]
I think this one is legit. So in the Godot phys engine, objects with zero linear damp will go in their direction forever. Likewise, zero angular damp should spin forever. In Godot Rapier both linear and angular slow over time with zero damp, tossing the first law of motion out the window like a baby with the bath water... or something.

Anything that moves in this project exhibits the behavior: https://github.com/GeminiSquishGames/Rapier2Dbug

Seems like Replace rather than Combine mode helps, but this isn't how Godot works. Pretty sure zero damp should let the object move forever unless acted upon in order to simulate it right... I think.

**Comment by Ughuuu** [comment]
Closing this and documenting in the readme that friction and bounce doesn't work same as in godot. After this will be fixed I will be able to make it work same:
https://github.com/dimforge/rapier/issues/622
